[build]
target = "x86_64_pythonos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"